-- Infinity Action Token schema
-- Additive extension for high-volume user interaction events.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS action_tokens (
    action_token_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    session_id TEXT,
    action_type TEXT NOT NULL,
    lane TEXT NOT NULL,
    source_token_id TEXT NOT NULL,
    destination_token_id TEXT,
    source_render_id TEXT,
    destination_render_id TEXT,
    profile_version INTEGER,
    observed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload_json TEXT,
    evidence_level TEXT NOT NULL DEFAULT 'OBSERVED',
    hourly_batch_id TEXT,
    FOREIGN KEY(source_token_id) REFERENCES tokens(token_id),
    FOREIGN KEY(destination_token_id) REFERENCES tokens(token_id)
);

CREATE INDEX IF NOT EXISTS idx_action_user_time
ON action_tokens(user_id, observed_at);
CREATE INDEX IF NOT EXISTS idx_action_source
ON action_tokens(source_token_id);
CREATE INDEX IF NOT EXISTS idx_action_destination
ON action_tokens(destination_token_id);
CREATE INDEX IF NOT EXISTS idx_action_lane
ON action_tokens(lane, observed_at);
CREATE INDEX IF NOT EXISTS idx_action_batch
ON action_tokens(hourly_batch_id);

CREATE TABLE IF NOT EXISTS hourly_action_batches (
    batch_id TEXT PRIMARY KEY,
    window_start TEXT NOT NULL,
    window_end TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_actions INTEGER NOT NULL DEFAULT 0,
    unique_users INTEGER NOT NULL DEFAULT 0,
    unique_tokens INTEGER NOT NULL DEFAULT 0,
    engineering_count INTEGER NOT NULL DEFAULT 0,
    assimilation_count INTEGER NOT NULL DEFAULT 0,
    import_count INTEGER NOT NULL DEFAULT 0,
    research_count INTEGER NOT NULL DEFAULT 0,
    decision_count INTEGER NOT NULL DEFAULT 0,
    repair_count INTEGER NOT NULL DEFAULT 0,
    report_json TEXT,
    checkpoint_commit_sha TEXT
);

CREATE TABLE IF NOT EXISTS action_relationships (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    source_token_id TEXT NOT NULL,
    destination_token_id TEXT NOT NULL,
    relationship_type TEXT NOT NULL,
    action_count INTEGER NOT NULL DEFAULT 1,
    confidence REAL NOT NULL DEFAULT 0.5,
    evidence_level TEXT NOT NULL DEFAULT 'INFERRED',
    explanation TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(batch_id) REFERENCES hourly_action_batches(batch_id),
    FOREIGN KEY(source_token_id) REFERENCES tokens(token_id),
    FOREIGN KEY(destination_token_id) REFERENCES tokens(token_id),
    UNIQUE(batch_id, user_id, source_token_id, destination_token_id, relationship_type)
);

CREATE TABLE IF NOT EXISTS action_paths (
    path_id TEXT PRIMARY KEY,
    batch_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    session_id TEXT,
    ordered_action_ids_json TEXT NOT NULL,
    ordered_token_ids_json TEXT NOT NULL,
    lane_sequence_json TEXT NOT NULL,
    derived_research_annotation_id INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(batch_id) REFERENCES hourly_action_batches(batch_id),
    FOREIGN KEY(derived_research_annotation_id) REFERENCES token_annotations(id)
);

CREATE TABLE IF NOT EXISTS pending_token_operations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    action_token_id TEXT NOT NULL,
    operation_type TEXT NOT NULL,
    source_token_id TEXT NOT NULL,
    destination_token_id TEXT,
    status TEXT NOT NULL DEFAULT 'PROPOSED',
    proposal_json TEXT,
    user_decision TEXT,
    resolved_at TEXT,
    resulting_commit_token_id TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(action_token_id) REFERENCES action_tokens(action_token_id),
    FOREIGN KEY(source_token_id) REFERENCES tokens(token_id),
    FOREIGN KEY(destination_token_id) REFERENCES tokens(token_id),
    FOREIGN KEY(resulting_commit_token_id) REFERENCES tokens(token_id)
);

-- Stable action IDs should be generated by the application from:
-- user + timestamp/event nonce + source token + destination token + action type.
-- They are ledger identifiers, not Git commit hashes.
